name: Builder rustLaunchSite

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

# needed for vcpkg caching
permissions:
  contents: write

# needed for vcpkg caching
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  rustLaunchSite:
    strategy:
      matrix:
        # only Windows for now
        os: [ windows-latest ]
        # only MinSizeRel for now
        buildtype: [ minsizerel ]
        include:
          # unique set of triplet(s) for each OS
          # NOTE: at least one triplet must be defined per OS
          - os: windows-latest
            triplet: x64-mingw-static-release

    name: ${{ github.workflow }}.${{ matrix.os }}.${{ matrix.triplet }}.${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    defaults:
      # use MSYS2 bash as the default shell
      run:
        shell: msys2 {0}

    env:
      # keep everyone on the same page regarding triplet when running vcpkg
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2.22.0
        with:
          msystem: MINGW64
          update: true
          install: >-
            curl
            git
            make
          pacboy: >-
            cmake:p
            ninja:p
            toolchain:p

      - name: Add MinGW64 to MSYS2 shell PATH
        run: export PATH="${RUNNER_TEMP}/msys64/mingw64/bin:${PATH}"

      # - name: Capture diagnostic info
      #   run: |
      #     which cmake && cmake --version
      #     which git && git --version
      #     which gcc && gcc --version
      #     set

      - name: Setup git line endings
        run: git config --global core.autocrlf input

      - name: Setup submodules
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: CMake configure
        run: cmake --preset ${{ matrix.triplet }}-${{ matrix.buildtype }}

      - name: CMake build
        run: cmake --build "${{ github.workspace }}/out/build/${{ matrix.triplet }}-${{ matrix.buildtype }}"
