name: rustLaunchSite

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

# needed for vcpkg caching
permissions:
  contents: write

# env vars common to all jobs
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # VCPKG_FEATURE_FLAGS: dependencygraph
  VCPKG_DISABLE_METRICS: true
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

jobs:
  build:
    strategy:
      matrix:
        include:
          - {os: windows-latest, tripletbase: x64-mingw-static,   buildtype: minsizerel, msystem: MINGW64, shell: "msys2 {0}", scrext: "sh" }
          - {os: windows-latest, tripletbase: x64-windows-static, buildtype: minsizerel, msystem: MSVC,    shell: "cmd",       scrext: "bat"}

    name: "${{ github.workflow }}.${{ matrix.os }}.${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
    runs-on: ${{ matrix.os }}

    env:
      SETENV: "${{ github.workspace }}/.github/scripts/setup.${{ matrix.scrext }}"
      VCPKG_DEFAULT_TRIPLET: "${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
      VCPKG_DEFAULT_HOST_TRIPLET: "${{ matrix.tripletbase }}-${{ matrix.buildtype }}"

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Setup MSVC Environment (1/2)
        if: ${{ matrix.msystem == 'MSVC' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x64
      - name: Setup MSVC Environment (2/2)
        if: ${{ matrix.msystem == 'MSVC' }}
        run: |
          choco install cmake git ninja

      - name: Setup MSYS2 Environment (1/2)
        if: ${{ matrix.msystem != 'MSVC' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            curl
            git
            make
          pacboy: >-
            cmake:p
            ninja:p
            toolchain:p
      - name: Setup MSYS2 Environment (2/2)
        if: ${{ matrix.msystem != 'MSVC' }}
        run: |
          git config --global core.autocrlf input

      - name: Setup git workspace
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          manifest-dir: "${{ github.workspace }}"
          triplet: "${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
          token: ${{ github.token }}
          github-binarycache: true

      - name: Configure project
        run: |
          ${{ env.SETENV }}
          cmake --preset "${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
      - name: Build project
        run: |
          ${{ env.SETENV }}
          cmake --build "${{ github.workspace }}/out/build/${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
      - name: Stage project
        run: |
          ${{ env.SETENV }}
          cmake --install "${{ github.workspace }}/out/build/${{ matrix.tripletbase }}-${{ matrix.buildtype }}"

      - name: Package and upload project
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.workflow }}-${{ github.job }}-${{ github.run_number }}-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
          path: "${{ github.workspace }}/out/install/${{ matrix.tripletbase }}-${{ matrix.buildtype }}"
